business:
  # （必须）项目名：此名称将决定make产生的成品文件在成品库中的名称，deploy阶段将使用此名称作为项目名进行部署
  project-name: {{projectName}}-components
  # （必须）项目部署位置
  public-url: //${hosts.component-registry-server}/{{projectName}}
  # 前端组件注册服务器主机
  component-registry-server: //${hosts.component-registry-server}
  # CDN服务器地址
  cdn: //${hosts.cdn}

gateway:
  djc:
